### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mlopez119** [praiman99/AutoScriptVPN#1]
menu not working.. when type menu nothing happen..

**Comment by praiman99** [comment]
can sent the screenshort of the error sorry late and what provider you used ?

**Comment by mlopez119** [comment]
Oh no.. I forgot to screenshot.. sorry.. I already delete the droplet.. im using digital ocean fyi

**Comment by praiman99** [comment]
Thank you for your info, for your information I'm also the same as you use the digital ocean provider from os debian 9 to 10. and everything goes well usually if not installed properly or not installed until the end. it may not be funtions on some tools I really appreciate if you can make a video on how you install this script on your vps. for me to fix all the visible damage however thank you very much for willing to use and report the problem and sorry for imperfections.

**Comment by mlopez119** [comment]
Will do later.. thanks for reply

**Comment by praiman99** [comment]
no probleam thanks again
